spring:
  application:
    name: atoj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 118.89.125.2:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        - id: atoj-backend-user-service
          uri: lb://atoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: atoj-backend-question-service
          uri: lb://atoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: atoj-backend-judge-service
          uri: lb://atoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive

server:
  port: 8101

knife4j:
  gateway:
    # 开启gateway聚合组件
    enabled: true
    # 设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # 开启discover模式
      enabled: true
      # 聚合子服务全部为Swagger2规范的文档
      version: swagger2